# Generated by Django 2.2.6 on 2019-10-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_auto_20191012_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
