# Generated by Django 2.2.6 on 2019-10-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200)),
                ('member_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_issue_date', models.CharField(max_length=200)),
                ('book_return_date', models.CharField(max_length=200)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.Author')),
            ],
        ),
    ]
