# Generated by Django 2.2.6 on 2019-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_member_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
