# Generated by Django 2.2.6 on 2019-10-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_member_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.Book'),
        ),
    ]
