# Generated by Django 2.2.6 on 2019-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_auto_20191014_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='book_issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='book_return_date',
            field=models.DateField(),
        ),
    ]
