# Generated by Django 2.2.6 on 2019-10-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_auto_20191014_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available1',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
