# Generated by Django 2.2.6 on 2019-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0009_book_available1'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
