# Generated by Django 2.2.6 on 2019-10-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0010_author_about_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='about_author',
        ),
    ]
